### ISSUE TITLE
[Feat] 알림 UI 구현 

### ISSUE THREAD

**Issue by pcsoyeon** [ThunderRing/ThunderRing-iOS#101]
## 💡 Issue
알림 탭 UI 구현 

## 📝  todo
- [x] 천둥/번개/취소 View 구현
- [x] 알림 탭 전체 UI 구조 구현
- [x] 데이터 구조/더미 데이터 -> 데이터 연동
