### ISSUE TITLE
[Feat] 알림 팝업 UI 구현 

### ISSUE THREAD

**Issue by pcsoyeon** [ThunderRing/ThunderRing-iOS#110]
## 💡 Issue
번개/취소 알림에 대한 팝업 UI를 구현합니다. 

## 📝  todo
- [ ] 번개 팝업 UI
- [ ] 취소 팝업 UI
- [ ] 알림에 따라 다른 팝업 화면 연결 
- [x] 디자인 QA 적용 
- [x] 데이터 연동
