### ISSUE TITLE
[Feat] 더미데이터 정리

### ISSUE THREAD

**Issue by pcsoyeon** [ThunderRing/ThunderRing-iOS#123]
## 💡 Issue
프로젝트 내 더미데이터 정리 및 시연에 필요한 데이터를 적용합니다. 
데이터를 변경하면서 해당 뷰에 맞는 분기처리 및 UI 수정도 진행합니다. 

## 📝  todo
- [x] 비공개그룹 더미데이터 수정
- [x] 비공개그룹 더미데이터 적용 + UI 수정 
- [x] 공개그룹 더미데이터 수정
- [x] 공개그룹 더미데이터 적용 + UI 수정
