### ISSUE TITLE
[Feat] 성향테스트 결과 UI 구현 

### ISSUE THREAD

**Issue by pcsoyeon** [ThunderRing/ThunderRing-iOS#128]
## 💡 Issue
성향 테스트 결과 UI를 구현합니다. 테스트 결과의 성향과 잘 어울리는 성향에 대한 데이터를 연동합니다.
추가로, 성향 테스트 답을 선택시에만 스크롤이 가능하도록 인터랙션을 수정합니다. 

## 📝  todo
- [x] 성향 테스트 결과 UI 구현
- [x] 성향 테스트 데이터 연동
- [ ] 스크롤 이슈 해결
