### ISSUE TITLE
[Hotfix] 성향테스트 인터랙션 및 결과 화면 수정 

### ISSUE THREAD

**Issue by pcsoyeon** [ThunderRing/ThunderRing-iOS#149]
## 💡 Issue
성향테스트 UI/인터랙션을 수정하고 더미데이터를 변경합니다. 

## 📝  todo
- [ ] 성향테스트 진행 인터랙션 수정 
- [ ] 선택한 내용에 맞게 결과 화면 수정 
- [ ] 더미 데이터 변경
