### ISSUE TITLE
[Feat] 그룹 상세 UI 구현 

### ISSUE THREAD

**Issue by pcsoyeon** [ThunderRing/ThunderRing-iOS#68]
## 💡 Issue
나의 비공개/공개 그룹 상세 UI 구현 

## 📝  todo
- [x] 전체 구조 구현 
- [x] 세부 Component 구현
- [x] 화면 연결
- [x] 이벤트 처리 
- [x] 공개/비공개 분기처리
