### ISSUE TITLE
[Feat] 모집중번개 수정 UI 구현 

### ISSUE THREAD

**Issue by pcsoyeon** [ThunderRing/ThunderRing-iOS#81]
## 💡 Issue
모집중번개 수정된 UI로 구현합니다. 

## 📝  todo
- [x] 스토리보드 -> 코드 베이스로 전환
- [x] 수정된 UI 적용 
- [ ] 화면 연결 및 인터랙션
