### ISSUE TITLE
[Feat] (수정된)그룹생성 UI 구현

### ISSUE THREAD

**Issue by pcsoyeon** [ThunderRing/ThunderRing-iOS#85]
## 💡 Issue
(수정된) 그룹생성 뷰 UI 구현

## 📝  todo
- [x] 네비게이션 수정
- [x] 공개그룹 생성 UI 수정
- [x] 비공개그룹 생성 UI 수정
- [ ] 코드 정리 (컨벤션 획일화/화면연결)
