### ISSUE TITLE
[Fix] 그룹생성 UI 수정 

### ISSUE THREAD

**Issue by pcsoyeon** [ThunderRing/ThunderRing-iOS#89]
## 💡 Issue
그룹 생성 UI 수정 (수정된 사항 반영)

## 📝  todo
- [x] 공개그룹 정원 warning label 추가
- [x] 공개그룹 정원 분기처리 인터랙션 추가
- [x] 비공개그룹 연락처 연동 UI 수정
